name: robokop
dependencies:
- python=3.6
- pip
- pip:
  - bcrypt
  - celery
  - eventlet
  - flask
  - flask-mail
  - flask-security
  - flask-sqlalchemy
  - flower
  - gunicorn
  - kombu
  - lru-dict
  - neo4j-driver
  - networkx==1.11
  - numpy>=1.8.0
  - psycopg2
  - psycopg2-binary
  - pymongo
  - pytest
  - redis

  # this may be interesting to explore:
  # https://conda.io/docs/user-guide/tasks/manage-environments.html#saving-environment-variables