name: covar-ncats
dependencies:
- python=3.6
- numpy>=1.8.0
- matplotlib
- scipy>=0.16.1
- scikit-learn>=0.14
- ipython
- pip
- pip:
  - neo4j-driver
  - flask
  - flask-security
  - flask-sqlalchemy
  - gunicorn
  - eventlet
  - psycopg2
  - psycopg2-binary
  - bcrypt
- nltk
- networkx=1.11
- nb_conda