version: "3"
services:
  manager:
    # image: patrickkwang/robokop
    build:
      context: .
    env_file:
      - ../../shared/robokop.env
    environment:
      - DEPLOY=docker
      - ROBOKOP_HOME=/home/murphy
      - NEO4J_HOST=neo4j
      - BROKER_HOST=broker
      - RESULTS_HOST=results
      - POSTGRES_HOST=postgres
      - BUILDER_HOST=interfaces
      - RANKER_HOST=rank
    ports:
      - "${MANAGER_PORT}:${MANAGER_PORT}"
      - "${FLOWER_PORT}:${FLOWER_PORT}"
      - "${SUPERVISOR_PORT}:${SUPERVISOR_PORT}"
    volumes:
      - ../../logs:/home/murphy/logs
      - ../../shared:/home/murphy/shared
      - ..:/home/murphy/robokop
networks:
  default:
    external:
      name: ${COMPOSE_PROJECT_NAME}_default