version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  manager:
    # image: patrickkwang/robokop
    build:
      context: .
    env_file:
      - ../../shared/robokop.env
    environment:
      - DEPLOY=docker
      - ROBOKOP_HOME=/home/murphy
      - NEO4J_HOST=neo4j
      - BROKER_HOST=broker
      - RESULTS_HOST=results
      - POSTGRES_HOST=postgres
      - BUILDER_HOST=interfaces
      - RANKER_HOST=rank
      - NLP_HOST=nlp
      - NLP_PORT=9475
    ports:
      - "${MANAGER_PORT}:${MANAGER_PORT}"
      - "${MANAGER_SUPERVISOR_PORT}:${MANAGER_SUPERVISOR_PORT}"
    volumes:
      - ../../logs:/home/murphy/logs
      - ../../shared:/home/murphy/shared
      - ..:/home/murphy/robokop
networks:
  default:
    external:
      name: ${COMPOSE_PROJECT_NAME}_default