apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: robokop-backend
  ports:
    # celery results port
    - name: celery-results-port
      protocol: TCP
      port: 6381
      targetPort: 6381
    # broker ports
    - name: broker-port
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: broker-http-port
      protocol: TCP
      port: 15672
      targetPort: 15672
    # nlp port
    - name: nlp-port
      protocol: TCP
      port: 9475
      targetPort: 9475