apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: robokop-logs-pv
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 10Gi
#    nfs:
#      path: /opt/robokop/logs
#      server: arrival.edc.renci.org
    hostPath:
      path: "/mnt/data/logs"
    persistentVolumeReclaimPolicy: Retain
    storageClassName: robokop-logs-pv
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: robokop-logs-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    storageClassName: robokop-logs-pv
kind: List