apiVersion: v1
kind: Service
metadata:
  name: manager
spec:
  selector:
    app: robokop-manager
  type: NodePort
  ports:
    #postgres
    - name: postgres-port
      protocol: TCP
      port: 5432
      targetPort: 5432
    # manager webservice
    - name: web-port
      protocol: TCP
      port: 80
      targetPort: 80
    # manager supervisor
    - name: supervisor-port
      protocol: TCP
      port: 9001
      targetPort: 9001
    # manager grapql port
    - name: graphql-port
      protocol: TCP
      port: 6498
      targetPort: 6498
    # pubmed cache
    - name: pubmed-cache-port
      protocol: TCP
      port: 6382
      targetPort: 6382