### Shared persistence volumes and claims to be used by most
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: robokop-postgres-pv
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 2Gi
#    nfs:
#      path: /opt/robokop/shared
#      server: arrival.edc.renci.org
    hostPath:
      path: "/mnt/data/postgres"
    persistentVolumeReclaimPolicy: Retain
    storageClassName: robokop-postgres-pv
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: robokop-postgres-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 2Gi
    storageClassName: robokop-postgres-pv
kind: List