apiVersion: apps/v1
kind: Deployment
metadata:
  name: robokop-proxy-deployment
  labels:
    app: robokop-manager
    service: robokop-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robokop-proxy
  template:
    metadata:
      labels:
        app: robokop-proxy
    spec:
      containers:
      - name: nginx-container
        image: renciorg/robokop_nginx_gateway:latest
        envFrom:
          - configMapRef:
              name: robokop-env
        ports:
          - containerPort: 443
        command:
          - '/startup.sh'
        volumeMounts:
          - mountPath: /var/log/nginx/
            name: logs-volume
          - mountPath: /etc/ssl/certs
            name: ssl-volume
      restartPolicy: Always
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: robokop-logs-pvc
        - name: ssl-volume
          persistentVolumeClaim:
            claimName: robokop-ssl-pvc