apiVersion: v1
kind: Service
metadata:
  name: robokop-proxy
spec:
  selector:
    app: robokop-manager
  type: NodePort
  ports:
    #postgres
    - name: robokop-proxy-port
      protocol: TCP
      port: 80
      targetPort: 80